name: GitHub Space Shooter Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza todo dia à meia-noite
  workflow_dispatch:      # Permite rodar manualmente

permissions:
  contents: write

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Necessário para o commit automático funcionar
      - uses: czl9707/gh-space-shooter@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: 'space-shooter.gif'
          strategy: 'random' # Táticas de ataque: pode ser 'random', 'column' ou 'row'
